CREATE DATABASE JSANCHEZMACSTORE
USE JSANCHEZMACSTORE
GO

CREATE TABLE USUARIO
(
IDUSUARIO INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
NOMBRE VARCHAR(50) NOT NULL,
APELLIDOPATERNO VARCHAR(50) NOT NULL,
APELLIDOMATERNO VARCHAR(50) NOT NULL,
EDAD INT NOT NULL,
EMAIL VARCHAR(250) NOT NULL,
CONTRASEÑA VARCHAR(50) NOT NULL
)
GO

CREATE PROCEDURE UsuarioAdd
@NOMBRE VARCHAR(50),
@APELLIDOPATERNO VARCHAR(50),
@APELLIDOMATERNO VARCHAR(50),
@EDAD INT,
@EMAIL VARCHAR(250),
@CONTRASEÑA VARCHAR(50)
AS
INSERT INTO USUARIO(NOMBRE,APELLIDOPATERNO,APELLIDOMATERNO,EDAD,EMAIL,CONTRASEÑA)
VALUES (@NOMBRE,@APELLIDOPATERNO,@APELLIDOMATERNO,@EDAD,@EMAIL,@CONTRASEÑA)
GO

CREATE PROCEDURE UsuarioUpdate
@IDUSUARIO INT,
@NOMBRE VARCHAR(50),
@APELLIDOPATERNO VARCHAR(50),
@APELLIDOMATERNO VARCHAR(50),
@EDAD INT,
@EMAIL VARCHAR(250),
@CONTRASEÑA VARCHAR(50)
AS
UPDATE USUARIO SET NOMBRE=@NOMBRE,APELLIDOPATERNO=@APELLIDOPATERNO,APELLIDOMATERNO=@APELLIDOMATERNO,EDAD=@EDAD,EMAIL=@EMAIL,CONTRASEÑA=@CONTRASEÑA
WHERE IDUSUARIO=@IDUSUARIO
GO

CREATE PROCEDURE UsuarioDelete
@IDUSUARIO INT
AS
DELETE FROM USUARIO WHERE IDUSUARIO=@IDUSUARIO
GO

CREATE PROCEDURE UsuarioGetAll
AS
SELECT IDUSUARIO,NOMBRE,APELLIDOPATERNO,APELLIDOMATERNO,EDAD,EMAIL,CONTRASEÑA FROM USUARIO
GO

CREATE PROCEDURE UsuarioGetById
@IDUSUARIO INT
AS
SELECT IDUSUARIO,NOMBRE,APELLIDOPATERNO,APELLIDOMATERNO,EDAD,EMAIL,CONTRASEÑA FROM USUARIO
WHERE IDUSUARIO=@IDUSUARIO
GO

CREATE PROCEDURE UsuarioGetByEmail --'Josesnx@gmail.com'
@EMAIL VARCHAR(250)
AS
SELECT IDUSUARIO,EMAIL,CONTRASEÑA FROM USUARIO WHERE EMAIL = @EMAIL
GO